### ISSUE TITLE
import error when i try easybase first time

### ISSUE THREAD

**Issue by pengyuan** [wgzhao/easybase#1]
In [1]: import easybase
  File "/usr/local/lib/python2.7/site-packages/easybase/table.py", line 381
    def delete(self, row, columns=None, timestamp=None, deletetype=1, attributes=None, durability=False):
      ^
IndentationError: expected an indented block

LOL

**Comment by wgzhao** [comment]
Sorry for that
I have fixit ,you can reinstall easybase to test,the latest version is 0.2

**Comment by pengyuan** [comment]
OK  3ks  :-D

wgzhao <notifications@github.com>于2017年11月14日 周二10:09写道：
