### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by rmekdma** [wgzhao/easybase#2]
Hi,
Do you have a plan to support python3?
I am using happybase, but it doesn't have time range scan. (sadbase 😄)
Supporting python3 will help me (and possibly others) a lot.

**Comment by wgzhao** [comment]
It has support Python3.x now

**Comment by xysscn** [comment]
when "pip install easybase" ,  got this error
 ERROR: Could not find a version that satisfies the requirement python>=2.7 (from easybase) (from versions: none)
ERROR: No matching distribution found for python>=2.7 (from easybase)
I use python 3.6 and pip 19.2
anyway, --no-dependencies works.

**Comment by wgzhao** [comment]
has fixed. you can try it again.
